# Site settings
title: Tomche Delev
email: tomce.delev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tdelev.github.io" # the base hostname & protocol for your site
twitter_username: tdelev
github_username:  tdelev
collections:
  event:
    output: true    
defaults:
  - scope:
      path: ""
      type: event
    values:
      layout: events
      icon: beer
# Build settings
markdown: kramdown
